### ISSUE TITLE
CommandBind.java:onTalk() 0c7864be4264bdb96e51ee0cd8223690b7c2324c

### ISSUE THREAD

**Issue by jeffry1829** [jeffry1829/MineChat#3]
log:
  console:
    At
   In0
   In1 [Ljava.lang.String;@5a543d41 |
   In2
   <player> yest
   At
   In0
   In1 [Ljava.lang.String;@8b93ec5 |
   In2
   <player> test
  playerlog:
    N
    <player> yest
    N
    <player> test

bindfile就好像完全沒有作用 並且回傳給玩家為定義在bindfile裡的 "N" or "y" 等無意義字串
明明println In1 + get[0] 卻沒有回傳一條正常的字串

**Comment by shirohana** [comment]
Maybe you can try this

```
@Override
public void onTalk(String msg , Player player) {
    try {
        BufferedReader br = new BufferedReader(new FileReader(bindfile));

        String line;
        while ( (line = br.readLine()) != null ){
            String[] pair = line.split("|");

            if (pair[0].equalsIgnoreCase(msg)) {
                player.sendMessage(pair[1]);
            }
        }
        br.close();
    } catch (Exception e) {}
}
```

**Comment by jeffry1829** [comment]
pair[0].equalsIgnoreCase(msg) 應該要改成 msg.contains(pair[0])

if那邊要break(吧?

並且回傳仍有問題

bindfile.bind

Nyan|pass
y|a
a|b
test|ttteeesssttttt

玩家輸入 Nyan 回傳 N
                                 y
                                 a
                                 t

**Comment by jeffry1829** [comment]
```
@Override
public void onTalk(String msg , Player player) {
    try {
        BufferedReader br = new BufferedReader(new FileReader(bindfile));

        String line;
        while ( (line = br.readLine()) != null ){
            String[] pair = line.split("|");
```

System.out.println(pair);
System.out.println(pair[0]+" 0");
System.out.println(pair[1]+" 1");
                if (msg.contains(pair[0])) {
                    player.sendMessage(pair[1]);
                    break;
                }

```
        }
        br.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

發現 pair[0]為空值
        pair[1]為第一個字母(例如 One|Two 回傳字母O)

**Comment by jeffry1829** [comment]
string.split()
|為分隔兩個分隔符號之用
欲使用|當分個符號須改為 "\|"
